Hatem fastapi task
AHL-Logics-backend-tranining-2024/fastapi-task pull request #8
Opened 2024-09-06 08:54 UTC by Hatem29

Created a small api for task creation and helping, with features including :
* UUID for each task uniqely identifing each task, with a specified set of statuses
* Urgent task implementation that has an extra field of specified set of priorities
* Multiple endpoints for reading the tasks created including one for reading urgent tasks
* Endpoints for creating, deleteing, and updating tasks
* Error handling features specifing to the user when and why an error happens
* Special response for each endpoint leveraging http stataus codes

2024-09-06 11:14 UTC, Mohammed-samaheen requested changes

2024-09-06 11:14 UTC, Mohammed-samaheen commented on Hatem/requirements.txt
Please ensure that you include the required packages in this file.

2024-09-07 16:21 UTC, Mohammed-samaheen commented on Hatem/requirements.txt
You didn't resolve this part.

2024-09-07 16:35 UTC, Hatem29 commented on Hatem/requirements.txt
got no idea why it doesn't show, it is there locally and I checked the git ignore files, nothing specified

2024-09-07 16:45 UTC, Mohammed-samaheen commented on Hatem/requirements.txt
gitignore will ignore the file itself. Could you please send me the details in the slack?

2024-09-08 14:27 UTC, Mohammed-samaheen approved these changes

2024-09-08 14:27 UTC, merged